# Generated by Django 5.1.4 on 2025-03-03 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_events_price'),
        ('MyTicket', '0004_alter_myticket_user'),
        ('Travels', '0002_travels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myticket',
            name='events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Events.events'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myticket',
            name='travels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travels.travels'),
        ),
    ]
