# Generated by Django 5.1.4 on 2025-03-03 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_events_price'),
        ('MyTicket', '0005_alter_myticket_events_alter_myticket_travels'),
        ('Travels', '0002_travels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myticket',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.events'),
        ),
        migrations.AlterField(
            model_name='myticket',
            name='travels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Travels.travels'),
        ),
    ]
