# Generated by Django 5.1.4 on 2025-03-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTicket', '0006_alter_myticket_events_alter_myticket_travels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myticket',
            name='travels',
        ),
    ]
