# Generated by Django 5.1.4 on 2025-03-05 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTicket', '0008_alter_myticket_events'),
        ('Travels', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myticket',
            name='travels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Travels.travels'),
        ),
    ]
