# Generated by Django 5.1.4 on 2025-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_events_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
