# Generated by Django 5.1.4 on 2025-02-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
